import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- 导入 SDK ---
from google import genai           # Gemini SDK
from openai import OpenAI          # DeepSeek 使用 OpenAI SDK 兼容
from tavily import TavilyClient

# ================= 配置区 =================
TEST_MODE = os.getenv("TEST_MODE", "False").lower() == "true"

# 获取 Keys
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY") # 新增

# 邮件配置 (163邮箱)
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")

# ================= 核心函数 =================

def get_mock_news():
    return [
        {"title": "DeepSeek V3 发布", "url": "https://deepseek.com", "content": "国产之光 DeepSeek 发布 V3 模型，性能强悍..."},
        {"title": "GitHub Copilot 更新", "url": "https://github.com", "content": "Copilot 现在支持更多语言..."}
    ]

def search_news(query):
    """使用 Tavily 搜索"""
    if TEST_MODE:
        return get_mock_news()

    print(f"🔍 正在调用 Tavily 搜索: {query}...")
    try:
        tavily = TavilyClient(api_key=TAVILY_API_KEY)
        response = tavily.search(
            query=query,
            search_depth="basic",
            topic="news",
            days=7,
            max_results=10, # 稍微增加一点数量
            include_raw_content=False
        )
        return response.get('results', [])
    except Exception as e:
        print(f"❌ 搜索失败: {e}")
        return []

def summarize_news(news_items):
    """智能总结：优先 DeepSeek，备用 Gemini"""
    if not news_items:
        return "本周没有找到相关新闻。"

    # 构建 Prompt
    news_content = "\n".join([f"- [{item['title']}]({item['url']}): {item['content']}" for item in news_items])
    
    prompt = f"""
    你是一个专业的科技主编。请根据以下 AI 新闻简讯，写一份中文周报。
    
    【要求】
    1. 标题清晰，分为【重磅头条】、【技术前沿】、【行业动态】三部分。
    2. 语言简练专业，不要废话。
    3. 必须保留原文链接。
    4. 结尾简述本周趋势。

    【新闻数据】
    {news_content}
    """

    # --- 策略 A: 优先使用 DeepSeek ---
    if DEEPSEEK_API_KEY:
        print("🤖 检测到 DeepSeek Key，正在调用 DeepSeek-V3 进行总结...")
        try:
            client = OpenAI(api_key=DEEPSEEK_API_KEY, base_url="https://api.deepseek.com/v1")
            response = client.chat.completions.create(
                model="deepseek-chat",  # DeepSeek V3
                messages=[
                    {"role": "system", "content": "你是一个专业的科技媒体编辑。"},
                    {"role": "user", "content": prompt},
                ],
                stream=False
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"❌ DeepSeek 调用失败: {e}")
            print("⚠️ 尝试切换回 Gemini...")
            # 如果 DeepSeek 失败，不返回，继续往下走尝试 Gemini

    # --- 策略 B: 备用 Gemini (保留原代码) ---
    if GEMINI_API_KEY:
        print("🤖 正在调用 Gemini (备用通道)...")
        try:
            client = genai.Client(api_key=GEMINI_API_KEY)
            # 使用最稳的 1.5 Flash
            response = client.models.generate_content(
                model="gemini-2.5-flash", 
                contents=prompt
            )
            return response.text
        except Exception as e:
            print(f"❌ Gemini 调用失败: {e}")
            return f"两大模型均调用失败。DeepSeek 错误已记录，Gemini 错误: {e}"
    
    return "❌ 未配置有效的 LLM API Key (DeepSeek 或 Gemini)。"

def send_email(subject, body):
    """发送邮件"""
    if not EMAIL_USER or not EMAIL_PASS:
        print("⚠️ 未配置邮件账户，跳过发送。")
        return

    msg = MIMEMultipart()
    msg['From'] = EMAIL_USER
    msg['To'] = EMAIL_TO
    msg['Subject'] = subject
    
    html_content = f"""
    <div style="font-family: sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #4A90E2;">🤖 AI News Weekly</h2>
        <pre style="white-space: pre-wrap; font-family: inherit; font-size: 14px;">{body}</pre>
        <hr style="margin: 20px 0;">
        <p style="font-size: 12px; color: #888;">Generated by GitHub Actions & DeepSeek/Gemini</p>
    </div>
    """
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))

    try:
        print(f"📧 正在连接 SMTP ({EMAIL_HOST})...")
        server = smtplib.SMTP_SSL(EMAIL_HOST, EMAIL_PORT)
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        print("✅ 邮件发送成功！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")

if __name__ == "__main__":
    keywords = "Artificial Intelligence LLM news last week"
    news_data = search_news(keywords)
    
    if news_data:
        report = summarize_news(news_data)
        today = datetime.now().strftime("%Y-%m-%d")
        send_email(f"AI周报 ({today})", report)
    else:
        print("没有获取到新闻数据。")