import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- 导入 SDK ---
from google import genai           # Gemini SDK
from openai import OpenAI          # DeepSeek 使用 OpenAI SDK 兼容
from tavily import TavilyClient

# ================= 配置区 =================
TEST_MODE = os.getenv("TEST_MODE", "False").lower() == "true"

# 获取 Keys
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

# 邮件配置 (163邮箱)
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 465
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
EMAIL_TO = os.getenv("EMAIL_TO")

# ================= 核心函数 =================

def get_mock_news():
    return [
        {"title": "DeepSeek V3.2 发布", "url": "https://deepseek.com", "content": "DeepSeek 发布 V3.2 版本，性能超越 GPT-4..."},
        {"title": "GitHub Copilot 更新", "url": "https://github.com", "content": "Copilot 智能体能力增强..."}
    ]

def search_news(query):
    """使用 Tavily 搜索"""
    if TEST_MODE:
        return get_mock_news()

    print(f"🔍 正在调用 Tavily 搜索: {query}...")
    try:
        tavily = TavilyClient(api_key=TAVILY_API_KEY)
        response = tavily.search(
            query=query,
            search_depth="basic",
            topic="news",
            days=7,
            max_results=10,
            include_raw_content=False
        )
        return response.get('results', [])
    except Exception as e:
        print(f"❌ 搜索失败: {e}")
        return []

def summarize_news(news_items):
    """智能总结：错误信息透传版"""
    if not news_items:
        return "本周没有找到相关新闻。"

    # 构建 Prompt
    news_content = "\n".join([f"- [{item['title']}]({item['url']}): {item['content']}" for item in news_items])
    
    prompt = f"""
    你是一个专业的科技主编。请根据以下 AI 新闻简讯，写一份中文周报。
    
    【要求】
    1. 标题清晰，分为【重磅头条】、【技术前沿】、【行业动态】三部分。
    2. 语言简练专业。
    3. 必须保留原文链接。
    4. 结尾简述本周趋势。

    【新闻数据】
    {news_content}
    """

    deepseek_error_msg = None  # 用于存储 DeepSeek 的报错

    # --- 策略 A: 优先使用 DeepSeek (V3.2) ---
    if DEEPSEEK_API_KEY:
        print("🤖 检测到 DeepSeek Key，正在调用 DeepSeek-V3.2 (deepseek-chat)...")
        try:
            client = OpenAI(
                api_key=DEEPSEEK_API_KEY, 
                base_url="https://api.deepseek.com" # 官方指定的 Base URL
            )
            response = client.chat.completions.create(
                model="deepseek-chat",  # 对应 V3.2 非思考模式
                messages=[
                    {"role": "system", "content": "你是一个专业的科技媒体编辑。"},
                    {"role": "user", "content": prompt},
                ],
                stream=False
            )
            return response.choices[0].message.content
        except Exception as e:
            deepseek_error_msg = str(e) # 抓住错误信息！
            print(f"❌ DeepSeek 调用失败: {deepseek_error_msg}")
            print("⚠️ 尝试切换回 Gemini...")

    # --- 策略 B: 备用 Gemini ---
    if GEMINI_API_KEY:
        print("🤖 正在调用 Gemini (备用通道)...")
        try:
            client = genai.Client(api_key=GEMINI_API_KEY)
            # 使用 1.5 Flash
            response = client.models.generate_content(
                model="gemini-2.5-flash", 
                contents=prompt
            )
            return response.text
        except Exception as e:
            gemini_error_msg = str(e)
            print(f"❌ Gemini 调用失败: {gemini_error_msg}")
            
            # 这里的修改是关键：如果两个都失败了，把两个错误都返回给你看
            error_report = "❌ 生成失败，所有模型均不可用。\n"
            if deepseek_error_msg:
                error_report += f"\n👉 [DeepSeek 报错]: {deepseek_error_msg}\n"
            error_report += f"👉 [Gemini 报错]: {gemini_error_msg}"
            
            return error_report
    
    # 如果 DeepSeek 挂了且没有配置 Gemini
    if deepseek_error_msg:
        return f"❌ DeepSeek 失败: {deepseek_error_msg}\n(且未配置 Gemini Key)"

    return "❌ 未配置有效的 LLM API Key。"

def send_email(subject, body):
    """发送邮件"""
    if not EMAIL_USER or not EMAIL_PASS:
        print("⚠️ 未配置邮件账户，跳过发送。")
        print(body)
        return

    msg = MIMEMultipart()
    msg['From'] = EMAIL_USER
    msg['To'] = EMAIL_TO
    msg['Subject'] = subject
    
    # 简单的 HTML 格式
    html_content = f"""
    <div style="font-family: sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #4A90E2;">🤖 AI News Weekly</h2>
        <pre style="white-space: pre-wrap; font-family: inherit; font-size: 14px;">{body}</pre>
        <hr style="margin: 20px 0;">
        <p style="font-size: 12px; color: #888;">Generated by GitHub Actions</p>
    </div>
    """
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))

    try:
        print(f"📧 正在连接 SMTP ({EMAIL_HOST})...")
        server = smtplib.SMTP_SSL(EMAIL_HOST, EMAIL_PORT)
        server.login(EMAIL_USER, EMAIL_PASS)
        server.send_message(msg)
        server.quit()
        print("✅ 邮件发送成功！")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")

if __name__ == "__main__":
    keywords = "Artificial Intelligence LLM news last week"
    news_data = search_news(keywords)
    
    if news_data:
        report = summarize_news(news_data)
        today = datetime.now().strftime("%Y-%m-%d")
        
        # 如果 report 开头是 "❌"，说明是报错信息，标题也改一下提醒自己
        subject_prefix = "⚠️ 出错: " if report.startswith("❌") else "🤖 AI周报"
        
        send_email(f"{subject_prefix} ({today})", report)
    else:
        print("没有获取到新闻数据。")